# -*- coding: utf-8 -*-
"""tombstone_text_extractor_easyocr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tpbfVizpelM64vTxJvAIcAHKlnZ8f_Oa
"""

!pip install "rembg[gpu]" easyocr imagehash opencv-python matplotlib



!pip install -U google-generativeai

import cv2
import numpy as np
import imagehash
from PIL import Image
import os
import matplotlib.pyplot as plt
import easyocr
from collections import defaultdict
from google.colab import files
import time
from rembg import remove
import time
import re
# Initialize EasyOCR
# WARNING: Ensure Colab Runtime is set to T4 GPU.
# If gpu=True fails to find a GPU, it falls back to CPU and speed plummets.
reader = easyocr.Reader(['en'], gpu=True)

import google.generativeai as genai

# Set up the API
# Replace 'YOUR_API_KEY_HERE' with your actual key
genai.configure(api_key="AIzaSyBO5xNoeVXbsYeEOFqewqWVpPqoi08Igew")

# We use gemini-1.5-flash because it is lightning fast and cheap/free
llm_model = genai.GenerativeModel('gemini-2.5-flash')


def generate_four_filters(gray_cropped_img):
    """Generates 4 distinct image processing styles for the ensemble OCR."""

    # 1. THE BASELINE (Just normal contrast)
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
    base = clahe.apply(gray_cropped_img)

    # 2. THE GRANITE FILTER (Bilateral + Morph Close)
    smoothed = cv2.bilateralFilter(gray_cropped_img, d=9, sigmaColor=75, sigmaSpace=75)
    granite = clahe.apply(smoothed)
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (2, 2))
    granite = cv2.morphologyEx(granite, cv2.MORPH_CLOSE, kernel)

    # 3. THE MARBLE FILTER (Median + Unsharp Mask)
    median = cv2.medianBlur(gray_cropped_img, 3)
    marble = clahe.apply(median)
    gaussian = cv2.GaussianBlur(marble, (0, 0), 2.0)
    marble = cv2.addWeighted(marble, 1.5, gaussian, -0.5, 0)

    # 4. THE DEEP CUT FILTER (Adaptive Binarization - pure black and white)
    deep_cut = cv2.adaptiveThreshold(
        base, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 11, 2
    )

    return [base, granite, marble, deep_cut]



def fix_text_with_ensemble_llm(ocr_results_list, max_retries=5):
    """Feeds 4 different OCR reads to Gemini, with an ultra-safe rate limit buffer."""

    reads_text = ""
    for i, text in enumerate(ocr_results_list):
        reads_text += f"\n--- OCR READ {i+1} ---\n{text if text else '[No text detected]'}\n"

    prompt = f"""
    You are an expert genealogist and archivist. I am scanning a heavily weathered gravestone.
    To get the best result, I ran 4 different image filters on the SAME stone.

    Please compare the 4 OCR reads below. They will have errors, but by cross-referencing them,
    synthesize the single most accurate transcription of the gravestone.

    - Correct obvious typos based on context ("Mlqmorv" -> "Memory").
    - Fix dates using logic.
    - Preserve the original line breaks as much as possible.
    - DO NOT add any conversational text. Output ONLY the final corrected text.

    {reads_text}
    """

    for attempt in range(max_retries):
        try:
            response = llm_model.generate_content(prompt)

            # INCREASED to 5 seconds.
            # This guarantees max 12 requests/min, keeping you safely under the 15 RPM limit.
            time.sleep(5)

            return response.text.strip()

        except Exception as e:
            error_msg = str(e)

            if "429" in error_msg or "quota" in error_msg.lower():
                match = re.search(r'retry in (\d+\.?\d*)s', error_msg)

                if match:
                    wait_time = float(match.group(1)) + 1.5 # Added a slightly larger safety buffer
                else:
                    wait_time = 30.0 * (attempt + 1)

                print(f"\n[!] Rate limit hit. Pausing for {wait_time:.1f} seconds (Attempt {attempt + 1}/{max_retries})...")
                time.sleep(wait_time)

            else:
                return f"[LLM Error: {e}]"

    return "[LLM Limit Error: Maximum retries exceeded. Please wait a minute and run again.]"


def auto_crop_text_region(img, padding=75):
    """
    Performs a lightning-fast OCR pass to find the text block,
    then crops the image down to just that region (with padding).
    """
    print("[*] Scouting for text region to auto-crop...")
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Scale down heavily for a super-fast scout pass
    scout_scale = 800.0 / max(gray.shape)
    scout_img = cv2.resize(gray, (0, 0), fx=scout_scale, fy=scout_scale)

    # Fast OCR pass (high threshold so we only catch obvious text blocks)
    results = reader.readtext(scout_img, text_threshold=0.4, adjust_contrast=False)

    if not results:
        print("[!] Scout pass couldn't find text. Skipping auto-crop.")
        return img

    # Find the extreme boundaries of all detected text
    min_x = min(min(pt[0] for pt in bbox) for bbox, _, _ in results)
    min_y = min(min(pt[1] for pt in bbox) for bbox, _, _ in results)
    max_x = max(max(pt[0] for pt in bbox) for bbox, _, _ in results)
    max_y = max(max(pt[1] for pt in bbox) for bbox, _, _ in results)

    # Scale coordinates back up to the original massive image size
    min_x = int(min_x / scout_scale)
    min_y = int(min_y / scout_scale)
    max_x = int(max_x / scout_scale)
    max_y = int(max_y / scout_scale)

    # Add padding and ensure we don't crop outside the image boundaries
    h, w = img.shape[:2]
    x_start = max(0, min_x - padding)
    y_start = max(0, min_y - padding)
    x_end = min(w, max_x + padding)
    y_end = min(h, max_y + padding)

    print("[*] Text region isolated. Zooming in.")
    return img[y_start:y_end, x_start:x_end]

def remove_gravestone_background(img):
    """
    Uses rembg to remove the background (grass, trees, etc.) and leaves
    only the main subject (the gravestone) on a black background.
    """
    print("[*] Removing background using rembg...")
    # rembg returns a BGRA image (with an alpha transparency channel)
    subject_only = remove(img)

    # If the image has an alpha channel, composite it over a black background
    if subject_only.shape[2] == 4:
        bgr = subject_only[:, :, :3]
        alpha = subject_only[:, :, 3]

        # Create a solid black background
        black_bg = np.zeros_like(bgr, dtype=np.uint8)

        # Create a boolean mask from the alpha channel
        mask = alpha > 0

        # Copy the subject onto the black background
        np.copyto(black_bg, bgr, where=mask[:, :, None])
        return black_bg

    return subject_only

def fix_orientation_smart(img):
    """
    Tests 4 rotational angles to find the correct orientation.
    Scores based on the length and confidence of alphanumeric text.
    This prevents false positives from large, garbage bounding boxes.
    """
    print("[*] Analyzing text orientation based on OCR confidence...")
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Scale down just for a faster orientation check (max 800px)
    max_dim = 800
    h, w = gray.shape
    if max(h, w) > max_dim:
        scale = max_dim / max(h, w)
        test_gray = cv2.resize(gray, (int(w * scale), int(h * scale)), interpolation=cv2.INTER_AREA)
    else:
        test_gray = gray

    # Quick contrast boost to help OCR see faint letters
    clahe = cv2.createCLAHE(clipLimit=2.5, tileGridSize=(8, 8))
    test_gray = clahe.apply(test_gray)

    best_rotation = 0
    best_score = 0

    rotations = [
        (0, None),
        (90, cv2.ROTATE_90_CLOCKWISE),
        (180, cv2.ROTATE_180),
        (270, cv2.ROTATE_90_COUNTERCLOCKWISE)
    ]

    for angle, cv2_rot_code in rotations:
        if cv2_rot_code is not None:
            test_img = cv2.rotate(test_gray, cv2_rot_code)
        else:
            test_img = test_gray

        # Run fast OCR pass
        results = reader.readtext(test_img, text_threshold=0.2, adjust_contrast=False)

        score = 0
        for (bbox, text, prob) in results:
            # Strip out symbols. We only care about letters and numbers.
            alphanumeric_text = "".join([c for c in text if c.isalnum()])

            if prob > 0.2 and len(alphanumeric_text) > 0:
                # Score is weighted by how long the word is AND how confident the AI is
                score += len(alphanumeric_text) * prob

        if score > best_score:
            best_score = score
            best_rotation = angle

    # GEOMETRIC FALLBACK: If OCR found absolutely zero valid text
    if best_score == 0:
        print("[!] OCR found no confident text. Falling back to geometric shape analysis...")
        _, thresh = cv2.threshold(gray, 5, 255, cv2.THRESH_BINARY)
        contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

        if contours:
            c = max(contours, key=cv2.contourArea)
            x, y, w, h = cv2.boundingRect(c)
            if w > (h * 1.1):
                print("[*] Stone is wider than it is tall. Auto-rotating 90 degrees.")
                best_rotation = 90
            else:
                print("[*] Stone aspect ratio looks upright.")
                best_rotation = 0

    elif best_rotation == 0:
        print(f"[*] Image is already upright (Confidence Score: {best_score:.2f}).")
    else:
        print(f"[*] Best orientation found at {best_rotation} degrees (Confidence Score: {best_score:.2f}).")

    # Apply the winning rotation to the ORIGINAL full-resolution color image
    if best_rotation == 90:
        return cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE)
    elif best_rotation == 180:
        return cv2.rotate(img, cv2.ROTATE_180)
    elif best_rotation == 270:
        return cv2.rotate(img, cv2.ROTATE_90_COUNTERCLOCKWISE)

    return img


    print(f"[*] Best orientation found at {best_rotation} degrees (Text Ratio: {best_text_ratio:.4f}).")

    # Apply the winning rotation to the original color image
    if best_rotation == 90:
        return cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE)
    elif best_rotation == 180:
        return cv2.rotate(img, cv2.ROTATE_180)
    elif best_rotation == 270:
        return cv2.rotate(img, cv2.ROTATE_90_COUNTERCLOCKWISE)

def get_image_sharpness(image_path):
    """Fast sharpness calculation."""
    img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    if img is None: return 0
    return cv2.Laplacian(img, cv2.CV_16S).var()

def cluster_images(image_paths, hash_threshold=5):
    """Groups duplicate images using Perceptual Hashing."""
    clusters = defaultdict(list)
    hashes = {}
    for path in image_paths:
        try:
            img = Image.open(path)
            h = imagehash.phash(img)

            matched_cluster = next((root for root in hashes if h - root <= hash_threshold), None)

            if matched_cluster:
                clusters[matched_cluster].append(path)
            else:
                hashes[h] = path
                clusters[h].append(path)
        except Exception as e:
            continue
    return clusters

def process_tombstone_fast(img):
    """High-speed DSP pipeline with Granite Noise Suppression."""

    # 1. Remove background first
    img = remove_gravestone_background(img)

    # 2. Fix orientation (Now safe from wide-base false positives)
    img = fix_orientation_smart(img)

    # 3. AUTO CROP
    img = auto_crop_text_region(img)

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # 4. Smart Resizing
    max_dim = 1500
    h, w = gray.shape
    if max(h, w) > max_dim:
        scale = max_dim / max(h, w)
        gray = cv2.resize(gray, (int(w * scale), int(h * scale)), interpolation=cv2.INTER_AREA)
        color_display = cv2.resize(img, (int(w * scale), int(h * scale)), interpolation=cv2.INTER_AREA)
    else:
        color_display = img.copy()

    # 5. GRANITE DENOISING: Bilateral Filter
    # Unlike Median blur, this smooths out stone speckles while keeping the edges of letters perfectly sharp.
    smoothed = cv2.bilateralFilter(gray, d=9, sigmaColor=75, sigmaSpace=75)

    # 6. Moderate Contrast Enhancement
    # We lower the clipLimit to 1.5 so we don't accidentally bring the speckles back
    clahe = cv2.createCLAHE(clipLimit=1.5, tileGridSize=(8, 8))
    enhanced = clahe.apply(smoothed)

    # 7. Morphological Closing
    # Granite often causes "breaks" in the letters. This bridges tiny gaps in the text.
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (2, 2))
    final_processed = cv2.morphologyEx(enhanced, cv2.MORPH_CLOSE, kernel)

    return color_display, final_processed

def extract_text_fast(processed_img):
    """Optimized EasyOCR execution with line-grouping and magnification."""

    # mag_ratio: Upscales the image internally by 1.5x to read tiny numbers
    # width_ths: Forces EasyOCR to group horizontal words together into lines
    # adjust_contrast: Turned back on because shadows inside engravings need local adjustment
    results = reader.readtext(
        processed_img,
        text_threshold=0.3,
        adjust_contrast=True,
        mag_ratio=1.5,
        width_ths=1.0
    )

    extracted_text, confidences = [], []
    for (bbox, text, prob) in results:
        # Lowered the strictness slightly because stone text is naturally low-confidence
        if prob > 0.15:
            extracted_text.append(text)
            confidences.append(prob)

    avg_conf = sum(confidences) / len(confidences) if confidences else 0
    return "\n".join(extracted_text), confidences, avg_conf




def run_speed_pipeline():
    """Execution function with Multi-Pass Ensemble OCR."""
    print("Please upload your tombstone images:")
    uploaded_files = files.upload()
    image_paths = list(uploaded_files.keys())

    if not image_paths: return

    start_total_time = time.time()

    if len(image_paths) > 1:
        print("Clustering duplicates...")
        clusters = cluster_images(image_paths)
        best_images = [max(paths, key=get_image_sharpness) for paths in clusters.values()]
        print(f"Reduced to {len(best_images)} unique images.")
    else:
        best_images = image_paths

    for img_path in best_images:
        img_start_time = time.time()

        original_img = cv2.imread(img_path)
        if original_img is None: continue

        # 1. Prep the image (Background -> Orientation -> Crop)
        bg_removed = remove_gravestone_background(original_img)
        oriented = fix_orientation_smart(bg_removed)
        cropped = auto_crop_text_region(oriented)

        gray_crop = cv2.cvtColor(cropped, cv2.COLOR_BGR2GRAY)

        # Resize the crop for speed/clarity
        max_dim = 1500
        h, w = gray_crop.shape
        if max(h, w) > max_dim:
            scale = max_dim / max(h, w)
            gray_crop = cv2.resize(gray_crop, (int(w * scale), int(h * scale)), interpolation=cv2.INTER_AREA)
            display_img = cv2.resize(cropped, (int(w * scale), int(h * scale)), interpolation=cv2.INTER_AREA)
        else:
            display_img = cropped.copy()

        # 2. Generate the 4 Filters
        filters = generate_four_filters(gray_crop)

        # 3. Run OCR on all 4 Passes
        print("[*] Running Ensemble OCR (4 Passes)...")
        all_ocr_texts = []
        for f_img in filters:
            text, _, _ = extract_text_fast(f_img)
            all_ocr_texts.append(text)

        # 4. Let the LLM figure out the truth from the 4 passes
        print("[*] Synthesizing final text with LLM...")
        final_clean_text = fix_text_with_ensemble_llm(all_ocr_texts)

        process_time = time.time() - img_start_time

        # Output Results
        print("\n" + "=" * 60)
        print(f"File: {img_path} | Processing Time: {process_time:.2f} seconds")

        # Print each raw read so you can see where they disagreed
        for i, ocr_text in enumerate(all_ocr_texts):
            print(f"\n--- Raw OCR Read {i+1} ---")
            print(ocr_text if ocr_text else "[No text]")

        print("\n" + "-" * 20 + " FINAL SYNTHESIZED TEXT " + "-" * 20)
        print(final_clean_text)
        print("=" * 60)

        # 5. Display the 4 filters dynamically
        fig, axs = plt.subplots(1, 5, figsize=(20, 4))
        axs[0].imshow(cv2.cvtColor(display_img, cv2.COLOR_BGR2RGB))
        axs[0].set_title("Cropped Original")
        axs[0].axis('off')

        filter_names = ["Base", "Granite", "Marble", "Deep Cut"]
        for i in range(4):
            axs[i+1].imshow(filters[i], cmap='gray')
            axs[i+1].set_title(filter_names[i])
            axs[i+1].axis('off')

        plt.tight_layout()
        plt.show()

    print(f"\nTotal Job Completed in {time.time() - start_total_time:.2f} seconds.")
# Run it
run_speed_pipeline()